cluster.name: docker-cluster
bootstrap.memory_lock: true
ES_JAVA_OPTS: -Xms512m -Xmx512m
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
discovery.type: single-node
http.port: 9200
transport.tcp.port: 9300
network.host: 0.0.0.0
http.host: 0.0.0.0
